services:
  agent-zero:
    container_name: agent-zero
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: main
    volumes:
      - ./agent-zero:/a0
    ports:
      - "50080:80"
